menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  关于: /about/ || fas fa-heart
# Typewriter Effect (打字效果)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: true
  colorful: true # open particle animation (冒光特效)
  shake: false #  open shake (抖動特效)
  mobile: false
local_search: 
  enable: true
search:
  path: search.xml
  field: post
  content: true
  template: ./search.xml
theme_color:
  enable: true
  main: "#226274"
preloader: true #加载动画
instantpage: false #预加载页面
readmode: false #阅读模式
pangu:
  enable: false
  field: post # site/post
index_img: https://pic.imgdb.cn/item/61ed09222ab3f51d91123705.jpg
footer_bg: true
beautify:
  enable: true
  field: site # site/post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: "#F47466"
canvas_nest:
  enable: true
  color: '34,98,116' #color of lines, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
  opacity: 0.7 # the opacity of line (0~1), default: 0.5.
  zIndex: -1 # z-index property of the background, default: -1.
  count: 199 # the number of lines, default: 99.
  mobile: false # false 手機端不顯示 true 手機端顯示
fireworks:
  enable: true
  zIndex: 9999 # -1 or 9999
  mobile: false
subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  # loop (循環打字)
  loop: true
  # source 調用第三方服務
  # source: false 關閉調用
  # source: 1  調用一言網的一句話（簡體） https://hitokoto.cn/
  # source: 2  調用一句網（簡體） http://yijuzhan.com/
  # source: 3  調用今日詩詞（簡體） https://www.jinrishici.com/
  # subtitle 會先顯示 source , 再顯示 sub 的內容
  source: false
  # 如果關閉打字效果，subtitle 只會顯示 sub 的第一行文字
  sub:
    - 一条爱捣鼓Android的咸鱼
    - 梦想总要有，万一实现了呢
    - 不积跬步，无以至千里
avatar:
  img: https://pic.imgdb.cn/item/61ed09222ab3f51d91123700.png
aside:
  enable: true
  hide: false
  button: true
  mobile: true # 手機頁面（ 顯示寬度 < 768px ）是否顯示aside內容
  position: right # left or right
  card_author:
    enable: true
    description: 一条有梦想的咸鱼
    button:
      enable: true
        icon：fab fa-github
      text: Github
      link: https://github.com/droidYu
  card_announcement:
    enable: true
    content: 我的个人博客正式开通啦！
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true